name: oauth-sheriff
description: A comprehensive framework for validating OAuth/JWT tokens in multi-issuer environments

release:
  current-version: 0.4.0
  next-version: 1.0.0-SNAPSHOT
  create-github-release: true

maven-build:
  java-versions: '["21","25"]'
  java-version: '21'
  enable-snapshot-deploy: true
  maven-profiles-snapshot: 'release-snapshot,javadoc'
  maven-profiles-release: 'release,javadoc'
  npm-cache: true

sonar:
  project-key: cuioss_OAuth-Sheriff
  enabled: true
  skip-on-dependabot: true

pages:
  reference: OAuth-Sheriff
  deploy-at-release: true

github-automation:
  auto-merge-build-versions: true
  auto-merge-build-timeout: 300

consumers:
  - nifi-extensions:version.oauth-sheriff

dependency-propagation:
  group-id: de.cuioss.sheriff.oauth
  artifact-id: oauth-sheriff-core
  scope: dependency
